### ISSUE TITLE
Migrate to .NET 6 LTS

### ISSUE THREAD

**Issue by CrendKing** [mann1x/CPUDoc#1]
I noticed that all your .NET projects uses .NET 5, which is currently end of life by Microsoft. Would you consider migrate them to .NET 6, which is a LTS version, for better maintainability and better security?

For this project specifically, I compiled locally with retargeting to .NET 6 without modifying any source code. So it should be a relatively effortless work.

**Comment by mann1x** [comment]
Hey,
Yes I'm considering it of course :)
Thanks for testing the retargeting!

I'll probably move to VS2022 and NET6 after this cycle of development.

There are 2 reasons why generally I keep using NET5; packages that are not working well or at all with NET6 and if I have problems generating a single file executable.
Right now the packages situation is getting better but a while ago I had to give up on something cause of these issues with the single file executable. And it should be better with NET6...

**Comment by mann1x** [comment]
Done!
Let me know if I missed something or any other suggestion.
Thx
