### ISSUE TITLE
Cut off set mask visualization on more than 16 cores

### ISSUE THREAD

**Issue by KyodaiKen** [mann1x/CPUDoc#2]
Beta 1.1.6

![image](https://user-images.githubusercontent.com/32415256/209155263-5f9315f2-5c92-4660-b946-eaa79ca5222e.png)

**Comment by mann1x** [comment]
Thanks, I will investigate!

**Comment by mann1x** [comment]
Indeed, at some point I changed the layout to 6 cores per column and forgot to add more columns.
Will be fixed in the next version, will ask you to test.
Thanks!

**Comment by KyodaiKen** [comment]
Awesome!

**Comment by mann1x** [comment]
Can you check with the 1.1.7b6 beta?

https://www.overclock.net/threads/cpudoc-little-cpu-helper-tool-with-some-exclusive-features.1802081/post-29104334

**Comment by KyodaiKen** [comment]
Due to my own security policies, I don't accept builds just from a Google Drive. Please push the sources to this GitHub repro, I will then compile it myself and test it. Thanks for understanding!

**Comment by mann1x** [comment]
No problem, it's a good strategy :)
I'm close to push the 1.1.8 to Github, let me know once you have tested it.

**Comment by mann1x** [comment]
Updated GH to 1.1.8, let me know if it works!

**Comment by KyodaiKen** [comment]
Unfortunately I can't compile, your nuget package "PowerManagerAPI-new101" seems to have been pulled from the package repository.

![image](https://user-images.githubusercontent.com/32415256/215729697-dbda12e5-6db2-48ad-b164-4074954e2cd6.png)

![image](https://user-images.githubusercontent.com/32415256/215729994-ddbe31c0-dfb6-468f-91ba-b6d736aea674.png)

**Comment by mann1x** [comment]
It's not there, I had to fix it cause it was missing some sub groups.
Download and compile manually the nuget package from my repo:

https://github.com/mann1x/PowerManagerAPI

Then add it manually to CPUDoc

**Comment by KyodaiKen** [comment]
Hi, finally could compile it. Never tried to install a local nupkg, took me a while.
It looks good now!

I will be switching to a 13900KS soon, it has less threads but the same amount of physical cores. Maybe you can find someone with a 5990X or so or an Epyc.

![image](https://user-images.githubusercontent.com/32415256/215735942-933f80b0-a864-4b9b-ad92-62c01263efaa.png)

**Comment by mann1x** [comment]
Makes sense to switch indeed... don't worry CPUDoc supports Intel 13th Gen as well :)
Would appreciate if you can enable and send me the logs as it's an uncommon platform!

**Comment by KyodaiKen** [comment]
Kinda offtopic, but it seems like you also had issues with Ryzen. Performance gets worse with each Windows Update, even on 10 as well, USB issues, Audio devices, random freezes from fTPM which is not being fixed by AMD on Threadripper, still no new AGESA since over a year... Also Zen2 is dated... Can't wait to get the water cooling done so I can switch to the 13900KS...

Yes I can send logs. By the way, the tool does not work on my Threadripper but I blame Windows/AMD for it. It even stops single core boost.

**Comment by mann1x** [comment]
Yeah, I'm pretty fed up as well about how quickly they forget "legacy" products.
But I didn't knew it was so bad with ThreadRipper...

Not sure why it doesn't work.
SSH should work regardless.
Maybe PSA? Try disabling it.
Could be there are specifics with TR that I don't cover with the power plan scheme.

**Comment by KyodaiKen** [comment]
Tried many combinations but I just guess the Windows scheduler is totally scuffed for Threadripper.

**Comment by mann1x** [comment]
Sad... decent hardware, bogged down by terrible software support.

**Comment by KyodaiKen** [comment]
Pretty much. Linux might work but since I got a 3090, which has a far too high memory clock on idle pulling 114W (sometimes also happens on Windows but enabling G-Sync fixes it there, not on Linux), I can't switch to Linux. I have AMD Ryzen running (5000G APUs) on my NAS and bedroom PC with Linux and have no issues.

**Comment by mann1x** [comment]
Wow, my 3090, Asus Strix, is pulling 56W on Windows with dual monitor.

I also have a 5600G on my NAS with Debian and it almost works very well.
Are you using my ryzen_smu and ryzen_monitor_ng?

Almost because most kernels doesn't work properly with the X570 board and crashing one SATA channel where I have one of the mdadm arrays.
Very sad, it's an old bug and never really fixed it... have to test every kernel release and go back to one that works if the array fails.

**Comment by KyodaiKen** [comment]
Manjaro and Ubuntu Server 22.04 LTS seem to have native Kernel support for Ryzen. I can make sensor panels on Manjaro KDE and see all detail I need there. s-tui also detects everything, except only overall power and only Core0 power. But overall power is enough for me to see.

Same 5600G in my NAS with an ASRock A520M Motherboard. 14W idle from the wall with a 10GBe Ethernet card and 4 4TB SATA SSDs, no issues there. Global C-State-Control does the magic! Unfortunately with it on, XMP becomes unstable. AMD's IMC is really crappy... But 2666 CL15 is fast enough for a NAS.

Also got the 3090 STRIX OC, with G-Sync on in Windows it idles at around 40W with a 1440p144 and an UHD 144Hz screen.

**Comment by mann1x** [comment]
No monitoring is ever going to be enough exhaustive for me :)

Anyway ryzen_monitor_ng can also control a lot of stuff for APU, like limits etc to further reduce and control power consumption.
I'm planning also to add a governor to adjust settings based on time (to keep power consumption lower during night) and usage, bit like CPUDoc PSA.

My NAS is actually a lot more close to a server than a NAS :P about 45W from the wall.
Cezanne IMC is pretty strong usually, if you have problems with XMP more likely either is the board weak or the voltages.
You need much much more SOC voltage on Linux than on Windows. 
If you are using anything below 1.20-1.25V probably it's the reason why it's not stable with XMP.

Had to use over 1.3V for 4200 MHz and it was drawing almost 55W so I went back to 3800 MHz.
Not that much of an advantage with the 5600G as the IMC bandwidth is overall limited.

**Comment by KyodaiKen** [comment]
I will give it a look and try when I convert my RAID0 to btrfs or zfs. Nonetheless, the many core display issue is fixed!
