### ISSUE TITLE
PowerSaveAktive on Alder Lake

### ISSUE THREAD

**Issue by ghost** [mann1x/CPUDoc#3]
On Alder Lake CPU in my Case 12900KS Twitch Streams beginn too Hang and Stuttering when Enable the PowerSaveAktive Feature on CPUDoc.
When i disalbe PowerSaveAktive all Stream run normal

**Comment by mann1x** [comment]
Could be, next version will have specific optimizations for streaming.
What are you using as GPU and software? OBS?

**Comment by Kafkasmoonlight** [comment]
I use a 3090ti TUF.. i´m not Streaming i showing only Twitch Streams. Testet the PowerSaveAktive on Chrome, Edge and Brave Browser all the same issue after a couple of Minutes

**Comment by mann1x** [comment]
Ah ok, got it.
Next version will have a Game Mode/Active Mode, it should fix this behavior.
Powerful CPUs tend to have a very light load also when gaming.
This triggers power optimizations.
It seems a bit weird they hang...
But let's see with the next version how it goes.

**Comment by mann1x** [comment]
Can you check with the 1.1.7b6 beta?

https://www.overclock.net/threads/cpudoc-little-cpu-helper-tool-with-some-exclusive-features.1802081/post-29104334

**Comment by Kafkasmoonlight** [comment]
I tested the current beta today and I have to say the hangers and stutters on Twitch. if I leave everything on automatic are gone.
The LowPower (PowerTweak setting) mode is too slow for a Twitch stream in 1080p, the stuttering is still there but not nearly as bad as in 1.16, which is very positive.
GameMode tools in the new beta work fine.
With regard to the Ryzen processors, I would like to see the implementation of the PBO2 tuner with the advantage that users simply save a lot of time setting up this tool than having to work through the readme see link.
https://github.com/PrimeO7/How-to-undervolt-AMD-RYZEN-5800X3D-Guide-with-PBO2-Tuner/blob/main/README.md

**Comment by mann1x** [comment]
Thanks for the feedback!
So if I understood correctly the problems watching the Twitch streams is gone with default settings using AutoPower. Comes back only if you set PowerTweak as LowPower.
Yes, everything that can be set in PBO2 Tuner will be available also on CPUDoc.
Plus even more settings, especially for APU.

**Comment by Kafkasmoonlight** [comment]
as soon as LowPower is activated, it doesn't take long and the stream seems to be in slow motion, as if someone had turned down the speed. And only then do the dropouts start over time. If I move my mouse, so any reaction takes place, then it also works with it, but I can't just watch the stream in this mode, I always have to do something on the side. It's almost as if the CPU sleeps so deeply in this mode that it no longer has the power to handle it.

**Comment by Kafkasmoonlight** [comment]
On the previews Version it makes no sens if i move my mouse or Not. The Stream beginn instandly stuttering. In that case is 1.17 a big forward

**Comment by mann1x** [comment]
I'm still not sure what is the problem now exactly, can you try to characterize it?
It's an improvement but not fixing it but I don't get what is the scenario when it doesn't work. Only when LowPower is selected?

Yes please, if you can enable logs and close & re-open and test would be nice.
Send me the content of the Logs folder.
And record when you start doing what and what happens.

I'm thinking maybe it's specific to Alder Lake and the E-Cores and parking.
If you can, please run QuickCPU and get a screenshot of the CPU Core Parking tab when it's stuttering:

![image](https://user-images.githubusercontent.com/20623405/212653937-65354d4a-aec7-4b5f-9d26-efcc6200fb95.png)

**Comment by mann1x** [comment]
Please check with latest v1.1.8 how it goes
