### ISSUE TITLE
reports high vsoc  on 7800x3d

### ISSUE THREAD

**Issue by bwanaaa** [mann1x/CPUDoc#7]
![cpudoc1004](https://user-images.githubusercontent.com/4876720/234997016-ad456a37-9c13-47f3-b312-d5cd6307e331.jpg)

**Comment by bwanaaa** [comment]
ASUS crosshair Hero 670E w default settings (no expo, no OC)

**Comment by mann1x** [comment]
Please refer to this issue if you still problems: #9

**Comment by Antag0nisticWomble** [comment]
> ASUS crosshair Hero 670E w default settings (no expo, no OC)

It looks like you're using an old bios version too which doesn't have full support for your CPU
