### ISSUE TITLE
CPUDoc not loading all the way.

### ISSUE THREAD

**Issue by d0mee1** [mann1x/CPUDoc#8]
Everytime i open the app it never loads all the way causing me to not be able to use it.

**Comment by mann1x** [comment]
Please try with this beta:

https://drive.google.com/file/d/17jsBA4T1HKacyOupivNiMDW9PAYTHjDm/view?usp=sharing

You probably have an AMD processor and an Antivirus which is blocking the inpoutx64.dll
You can try whitelisting the dll or the CPUDoc folder but some AV, like Kaspersky, have decided to block it even when whitelisted.
There is an command line switch documented which will disable loading of the DLL but you will loose all the AMD specific features.

**Comment by mann1x** [comment]
Please refer also to this issue if you still have problems:

https://github.com/mann1x/CPUDoc/issues/9
