### ISSUE TITLE
Program interface is Not responding every couple seconds

### ISSUE THREAD

**Issue by usbongman** [mann1x/CPUDoc#9]
Hello im currently having an issue whenever i launch the program, itll load fine until i click into the interface then itll freeze after a couple of seconds, go unresponsive, then become responsive for a few more seconds then go unresponsive.
Im currently using the 'CPUDoc-v1.2.10-dev-b26' version as any previous version would not like me load.
When i first launched the program before restart, it only displayed my CPU model, Board model but missing system, processors, memory displays, but was working completely fine without any freezes.
I do have Kaspersky AV, already set to exclusion on the dll and folder, tried disabling.
I have the .net 6 installed, im really not sure whats causing this, and im sorry if i couldnt explain my problem further
Ive enabled diagnostic logs and can only product these files

[LogFile.txt](https://github.com/mann1x/CPUDoc/files/11790042/LogFile.txt)
[LogTrace.txt](https://github.com/mann1x/CPUDoc/files/11790043/LogTrace.txt)

![image](https://github.com/mann1x/CPUDoc/assets/137090482/f3701308-fd0f-4f81-8350-5b8796426d93)

**Comment by mann1x** [comment]
That's because the UI interface is not yet asynchronous with the refresh of the sensors.
It makes it easier to spot problems, like in your case.
The inpoutx64.dll is either blocked by the Antivirus or by a vCore/vSOC voltage override in BIOS.

You can use the "inpoutdlldisable" command line switch but you will loose ZenControl and all the AMD specific settings.

Otherwise you can try to whitelist the CPUDoc folder in the AV but in some cases doesn't work, like with Kaspersky.
It just ignores the whitelisting.

If it's the BIOS you need to remove the override of the voltage or set another one.
On MSI boards the "AMD Overclocking" is blocking the SMU, the "Override" and "Override + Offset" types doesn't.

**Comment by Antag0nisticWomble** [comment]
> Hello im currently having an issue whenever i launch the program, itll load fine until i click into the interface then itll freeze after a couple of seconds, go unresponsive, then become responsive for a few more seconds then go unresponsive. Im currently using the 'CPUDoc-v1.2.10-dev-b26' version as any previous version would not like me load. When i first launched the program before restart, it only displayed my CPU model, Board model but missing system, processors, memory displays, but was working completely fine without any freezes. I do have Kaspersky AV, already set to exclusion on the dll and folder, tried disabling. I have the .net 6 installed, im really not sure whats causing this, and im sorry if i couldnt explain my problem further Ive enabled diagnostic logs and can only product these files
> 
> [LogFile.txt](https://github.com/mann1x/CPUDoc/files/11790042/LogFile.txt) [LogTrace.txt](https://github.com/mann1x/CPUDoc/files/11790043/LogTrace.txt)
> 
> ![image](https://user-images.githubusercontent.com/137090482/246876683-f3701308-fd0f-4f81-8350-5b8796426d93.png)

I had this issue earlier. Updated AMD chipset drivers and rebooted now it works properly.

**Comment by mann1x** [comment]
@Antag0nisticWomble 

Thanks for sharing, I had no idea also the chipset drivers could cause this issue...

**Comment by Antag0nisticWomble** [comment]
> @Antag0nisticWomble
> 
> Thanks for sharing, I had no idea also the chipset drivers could cause this issue...

Yea I had the same issue with fancontroller not working correctly due to not having the correct SMBus driver installed.

**Comment by mann1x** [comment]
@usbongman 

I see you are using Kasperky, you may have to get rid of it to use any homegrown tool for Zen.
I had to remove it a few weeks ago myself, they decided to brutally block the dll and it's impossible to whitelist.
You should have the same issue with ZenTimings and PBO2Tuner.

**Comment by mann1x** [comment]
> > @Antag0nisticWomble
> > Thanks for sharing, I had no idea also the chipset drivers could cause this issue...
> 
> Yea I had the same issue with fancontroller not working correctly due to not having the correct SMBus driver installed.

In theory access to SMU shouldn't need any driver, it's direct via PCI, but I never really tried...

**Comment by usbongman** [comment]
Hello, thanks for your guy's advice, listened and reinstalled Chipset drivers and removed Kaspersky and everything was working fine now. I really appreciate your guys help! :) 
Also fixed my readings on PBO2Tuner as it wouldn't display my pbo limits at all besides MaxBoost and FIT scalar, Thanks again :)

**Comment by mann1x** [comment]
Wonderful!
Good luck testing :)
